version: "24.0.2"
services:
  #Configuration de eureka container
  eureka:
    build:
      context: ./eureka
    ports:
      - "8761:8761"
    image: "eureka_image"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka/


  #Configuration de Projetmicro container
  reclamation:
    build:
      context: ./Reclamation
    ports:
      - "8080:8080"
    image: "projet_microservice_image"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka/
    depends_on:
      - eureka
      - docker-mysql_1

  #configuration de mysql container
  docker-mysql_1:
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=reclamation_microservice
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306


  #Configuration de Gateway container
  getway:
    build:
      context: ./Getway
    ports:
      - "7000:7000"
    image: "gateway_image"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka/
    depends_on:
      - eureka
      - reclamation